config:
  gcp:project: variant-processing
  gcp:region: us-central1
  vap-ui:project_id: variant-processing
  vap-ui:region: us-central1
  vap-ui:image_tag: latest
encryptionsalt: v1:4LZbZpoWRpg=:v1:KDgVXRTFYR+cNoqd:Mxe0EEOycJgO9sUR4eSq1PKymK1g1Q==
